name: Install System Dependencies
description: Install System dependencies for Filecoin Lotus

runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ocl-icd-opencl-dev libhwloc-dev pkg-config
      shell: bash
    - if: runner.os == 'macOS'
      env:
        HOMEBREW_NO_AUTO_UPDATE: '1'
      run: |
        brew install hwloc pkg-config
      shell: bash
