name: Release

on:
  push:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out lotus
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Install Go (archives generation dependency)
        uses: ./.github/actions/install-go
      - name: Install zsh (changelog generation dependency)
        run: sudo apt update && sudo apt install -y zsh
      - name: Generate changelog
        id: changelog
        env:
          previous: v1.15.2-rc1
          current: 7e6c72e312f8da5052d6c4613af608bab3ca421c
        run: |
          echo "content<<EOF" | tee -a $GITHUB_OUTPUT
          echo "$(go env GOPATH)/src/github.com/filecoin-project/lotus"
          mkdir -p "$(go env GOPATH)/src/github.com/filecoin-project/lotus"
          rm -rf "$(go env GOPATH)/src/github.com/filecoin-project/lotus"
          ln -s "$(pwd)" "$(go env GOPATH)/src/github.com/filecoin-project/lotus"
          ./scripts/mkreleaselog "$previous" "$current" | tee -a $GITHUB_OUTPUT
          echo "EOF" | tee -a $GITHUB_OUTPUT
