name: Release

# TODO(p2): Restore worfklow_dispatch trigger
on:
  push:
    branches:
      - release/v*
      - releases
    paths:
      - build/version.go
  pull_request:
    branches:
      - release/v*
      - releases
    paths:
      - build/version.go

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  check:
    name: Check which projects need to be built
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.projects.outputs.projects }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: projects
        env:
          TARGET_REF: ${{ github.base_ref || github.ref }}
        run: |
          go run cmd/release/main.go --json list-projects | jq -r '.msg' |
            jq 'map(select(.version | endswith("-dev") | not))' |
            jq 'map(select(.released | not))' |
            jq 'map(select(env.TARGET_REF == "refs/heads/releases" and .prerelease | not))' |
            xargs -I {} echo "projects={}" |
            tee -a $GITHUB_OUTPUT
  build:
    needs: [check]
    if: needs.check.outputs.projects != '[]'
    name: Build ${{ fromJSON(matrix.project).name }} (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.check.outputs.projects) }}
        runner:
          - ubuntu-latest # Linux X64
          - macos-13 # MacOs X64
          - macos-14 # MacOS ARM64
    steps:
      - run: echo "Building on $RUNNER_OS/$RUNNER_ARCH"
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/install-system-dependencies
      - uses: ./.github/actions/install-go
      - env:
          GITHUB_TOKEN: ${{ github.token }}
        run: make deps
      - if: fromJSON(matrix.project).name == 'node'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: make lotus
      - if: fromJSON(matrix.project).name == 'miner'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: make lotus-miner lotus-worker
      - if: runner.os == 'macOS'
        run: if [[ -f lotus ]]; then otool -hv lotus; fi
      - env:
          LOTUS_VERSION_IGNORE_COMMIT: 1
          expected: ${{ fromJSON(matrix.project).version }}
        run: |
          for bin in lotus lotus-miner lotus-worker; do
            if [[ -f ./$bin ]]; then
              chmod +x ./$bin
              actual=$(./$bin --version | cut -d' ' -f3)
              if [[ "$actual" != "$expected" ]]; then
                echo "::error title=Version Mismatch::Expected $expected, got $actual (./$bin)"
                exit 1
              fi
            fi
          done
      - uses: actions/upload-artifact@v4
        with:
          name: lotus-${{ fromJSON(matrix.project).name }}-${{ runner.os }}-${{ runner.arch }}
          path: |
            lotus
            lotus-miner
            lotus-worker
  release:
    needs: [check, build]
    if: needs.check.outputs.projects != '[]'
    name: Release [publish=${{ github.event_name != 'pull_request' }}]
    permissions:
      # This enables the job to create and/or update GitHub releases
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.check.outputs.projects) }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: lotus-${{ fromJSON(matrix.project).name }}-Linux-X64
          path: linux_amd64_v1
      - uses: actions/download-artifact@v4
        with:
          name: lotus-${{ fromJSON(matrix.project).name }}-macOS-X64
          path: darwin_amd64_v1
      - uses: actions/download-artifact@v4
        with:
          name: lotus-${{ fromJSON(matrix.project).name }}-macOS-ARM64
          path: darwin_arm64
      - uses: ./.github/actions/install-go
      - uses: ipfs/download-ipfs-distribution-action@v1
        with:
          name: kubo
          version: v0.16.0
      - run: pip install yq
      - if: github.event_name != 'pull_request'
        run: yq -i '.release.draft = false' .goreleaser.yaml
      - if: fromJSON(matrix.project).name == 'node'
        run: yq -i '.builds | map(select(.id == "lotus"))[0].skip = false' .goreleaser.yaml
      - if: fromJSON(matrix.project).name == 'miner'
        run: |
          yq -i '.builds | map(select(.id == "lotus-miner"))[0].skip = false' .goreleaser.yaml
          yq -i '.builds | map(select(.id == "lotus-worker"))[0].skip = false' .goreleaser.yaml
      - uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5.0.0
        with:
          distribution: goreleaser-pro
          version: 2.0.1
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          TAG: ${{ fromJSON(matrix.project).tag }}
          VERSION: ${{ fromJSON(matrix.project).version }}
          IS_LATEST: ${{ fromJSON(matrix.project).latest }}
          IS_DRAFT: ${{ github.event_name == 'pull_request' }}
          IS_PRERELEASE: ${{ fromJSON(matrix.project).prerelease }}
          TARGET_COMMITISH: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.sha }}
          HEADER: '' # TODO(p3): Extract release notes from CHANGELOG.md
      - run: ./scripts/generate-checksums.sh
      - env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG: ${{ fromJSON(matrix.project).tag }}
        run: ./scripts/publish-checksums.sh
